### ISSUE TITLE
混淆这里是怎么处理的呢?

### ISSUE THREAD

**Issue by gflkdns** [feelschaotic/SDKHotFix#1]
SDK要求发给客户的是混淆包. 每次编译都有可能不同 , 有没有对于这块的处理能分享下 ?  也就是宿主v1.0 中的 Config.class  发包的时候可能是 A.class ,  那么热修包中的 应该是A.class 还是 Config.class 还是说没有影响无所谓?

Sorry 还没来得及好好看代码?希望解惑 (*￣︶￣)

**Comment by gflkdns** [comment]
简而言之就是 , 能不能满足混淆的场景? 有没有额外的问题?

**Comment by feelschaotic** [comment]
你好，对于 SDK 混淆：

- 二方库：如果是使用`proguard`，产物`mapping.txt`映射文件保存好，在生成补丁时放在目录下即可。
- 三方库：拿不到宿主的`mapping.txt`，这需要 SDK 考虑好热修的范围，配置好consumerProguardFiles，指定宿主在构建时对SDK使用的混淆规则，像一些用到的第三方库如网络请求的热修概率不大，就可以无需`keep`，后续会考虑做个脚本，根据SDK依赖的包自动生成keep规则。

本项目更推荐二方库使用。

**Comment by gflkdns** [comment]
好的,了解,感谢解答 !
