### ISSUE TITLE
在other下点击assembleRelease打包时，出现错误

### ISSUE THREAD

**Issue by BeiHaiCoding** [feelschaotic/SDKHotFix#10]
![QQ截图20200822164443](https://user-images.githubusercontent.com/30135449/90952520-cd5ef080-e496-11ea-920d-e612b3d0dbca.png)

gradle使用的是classpath 'com.android.tools.build:gradle:3.5.2'

其他配置都是按demo的来

**Comment by fza3230200** [comment]
@BeiHaiCoding  您好,请问您最后怎么解决的呢?
