### ISSUE TITLE
execute command    java -jar robust\dx.jar --dex --output=classes.dex  meituan.jar error

### ISSUE THREAD

**Issue by HDZZZ** [feelschaotic/SDKHotFix#11]
打补丁时，assembleRelease Gradle 遇到一个问题

* What went wrong:
Execution failed for task ':hotfixSDK:transformClassesWithAutoPatchTransformForRelease'.
> execute command    java -jar E:\Android Project\RewardLotteryApp\hotfixSDK\robust\dx.jar --dex --output=classes.dex  meituan.jar error

classpath "com.android.tools.build:gradle:3.0.1"
gradle-4.4-all

**Comment by feelschaotic** [comment]
jdk环境是多少呢？

**Comment by HDZZZ** [comment]
1.8.0_152-release

**Comment by feelschaotic** [comment]
看看这对你是否有帮助

https://github.com/Meituan-Dianping/Robust/issues/55

**Comment by HDZZZ** [comment]
没有，这些事情我都尝试过了，并没有帮助。
美团的robust库我也看过了，对我并没有帮助

**Comment by HDZZZ** [comment]
可以给我下你的邮箱之类的么，这样讨论效率有点低

**Comment by feelschaotic** [comment]
feelschaotic@gmail.com

**Comment by feelschaotic** [comment]
可以替换dx.jar 试试   [下载地址](http://note.youdao.com/s/V02hjSNR)
