### ISSUE TITLE
1.12版本引用失败

### ISSUE THREAD

**Issue by BeforeFuture** [feelschaotic/SDKHotFix#16]
1.12版本引用失败
implementation 'com.github.feelschaotic:SDKHotFix:1.10-RELEASE'，引用就正常，

改为
implementation 'com.github.feelschaotic:SDKHotFix:1.12-RELEASE'，就会失败，大佬快看下什么原因吧！

**Comment by feelschaotic** [comment]
我的锅   这两次版本忘记在管理后台release一下了   我晚上回去重新发布下

**Comment by BeforeFuture** [comment]
> 我的锅 这两次版本忘记在管理后台release一下了 我晚上回去重新发布下

我以为是我gradle版本的问题，搞了半天发现都不行，最后改了版本号可以了。

**Comment by BeforeFuture** [comment]
> 我的锅 这两次版本忘记在管理后台release一下了 我晚上回去重新发布下

大佬再问个问题，我可以把补丁手动放到自己的服务器上，然后让SDK自动去下载吗？

**Comment by feelschaotic** [comment]
可以的，需要修改SDK请求的接口，从请求bomb改为你们自己服务地址即可

**Comment by feelschaotic** [comment]
> 1.12版本引用失败
> implementation 'com.github.feelschaotic:SDKHotFix:1.10-RELEASE'，引用就正常，
> 
> 改为
> implementation 'com.github.feelschaotic:SDKHotFix:1.12-RELEASE'，就会失败，大佬快看下什么原因吧！

已解决  可以重试拉依赖

**Comment by BeforeFuture** [comment]
> > 1.12版本引用失败
> > implementation 'com.github.feelschaotic:SDKHotFix:1.10-RELEASE'，引用就正常，
> > 改为
> > implementation 'com.github.feelschaotic:SDKHotFix:1.12-RELEASE'，就会失败，大佬快看下什么原因吧！
> 
> 已解决 可以重试拉依赖

1.12已经可以拉取！

**Comment by BeforeFuture** [comment]
> 可以的，需要修改SDK请求的接口，从请求bomb改为你们自己服务地址即可

![image](https://user-images.githubusercontent.com/22706063/104898572-c3dda400-59b4-11eb-9110-dc15e207f842.png)
大佬， 下载补丁地址是在SDK的BuildConfig里：HOTFIX_SERVER_URL = "https://api.bmob.cn/1/functions/"，这个地址貌似我无法通过代码修改，请教一下，要怎么操作，去修改这个补丁下载地址？

**Comment by feelschaotic** [comment]
sdk源码都开源了，你可以直接修改sdk源码，且替换成你们自己的maven管理，重新打包就可以了
