### ISSUE TITLE
Didn't find class

### ISSUE THREAD

**Issue by LeeTech** [feelschaotic/SDKHotFix#2]
小姐姐你好：
     十分感谢你提供了一个方便接入Robust的方案。
     在接入过程中，我遇到一些问题：

RobustCallBack提示异常: throwable=Didn't find class "com.feelschaotic.sdkhotfix.sdk.PatchManipulateImp.PatchesInfoImpl"

![image](https://user-images.githubusercontent.com/18023710/76853429-31e2a780-6888-11ea-825e-b3c6ec190aba.png)
在classLoader补丁包时，没有找到相应的类，通过追踪源码，需要加载的类名如下：
![image](https://user-images.githubusercontent.com/18023710/76853677-baf9de80-6888-11ea-8b92-ca51962915da.png)
在module sdk中并没有发现该类，是我接入的方式有问题吗，感谢提供解决方案。

**Comment by feelschaotic** [comment]
你好，提供下项目中robust.xml配置文件，我看看配置是否有问题，还有另外一个排查方式 —— 直接反编译补丁，看补丁里是否有这个类且包名一致

**Comment by LeeTech** [comment]
robust.xml相关配置如下：
![image](https://user-images.githubusercontent.com/18023710/76921384-e6241280-6908-11ea-86e4-d7c444cbcf2a.png)
源码是直接checkout下来的，没有任何改动。

**Comment by feelschaotic** [comment]
发送补丁（未加密版）到我的邮箱吧 feelschaotic@gmail.com，我反编译看看包名有没有对上。

**Comment by LeeTech** [comment]
> 发送补丁（未加密版）到我的邮箱吧 [feelschaotic@gmail.com](mailto:feelschaotic@gmail.com)，我反编译看看包名有没有对上。

邮件已发生，烦请小姐姐查收。
