### ISSUE TITLE
build时执行transformClassesWithRobustForRelease失败, java.io.IOException: invalid constant type: 19 at 5

### ISSUE THREAD

**Issue by directionyu** [feelschaotic/SDKHotFix#3]
异常类型：编译异常

Robust版本：如:0.4.87.5

Gradle版本：如:3.2.0

系统：如:mac

堆栈/日志：

Task :middleware:transformClassesWithRobustForRelease
================robust start================
read all class file cost 0.4 second

Task :middleware:transformClassesWithRobustForRelease FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':middleware:transformClassesWithRobustForRelease'.
java.io.IOException: invalid constant type: 19 at 5

**Comment by directionyu** [comment]
使用你的com.github.feelschaotic:SDKHotFix:1.6-RELEASE 构建无问题, 使用自己更改OSS等账户的库报错.

**Comment by directionyu** [comment]
将源码工程导入,替换Res 构建插桩jar 没问题....奇怪了..

**Comment by feelschaotic** [comment]
1.6的 bmob 云函数服务在2020-04-09 12:05:21 过期了，请使用1.7试试。（若过期，无法更新补丁信息、无法请求拉取补丁）
