### ISSUE TITLE
Gradle版本兼容性问题很多坑, 3.2.0 hookBundle 有问题

### ISSUE THREAD

**Issue by directionyu** [feelschaotic/SDKHotFix#4]

**Comment by directionyu** [comment]
error：could not get unknown property 'bundleRelease' for object of type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication

将bundleRelease修改为bundleReleaseAar

**Comment by feelschaotic** [comment]
对，打包用到了很多 hook Task 的方式，无可避免要面向 Gradle API 编程，版本兼容是个坑，欢迎提个 pr
