### ISSUE TITLE
AES解密报错:javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH

### ISSUE THREAD

**Issue by directionyu** [feelschaotic/SDKHotFix#5]
私钥解密后 密文是正确的,但是解密文件时报错
javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH

**Comment by feelschaotic** [comment]
你好，这种情况之前遇到过，因为补丁被重复加密了。

所以首先要确定，是否有存在补丁被重复加解密的情况，第一步，复制未加密的patch.jar到根目录下，第二步点击gradleTask上传，此时，会对jar进行加密，所以根目录下 patch.jar实际上已经被修改了（文件同名，因为时间关系，没有扩展为不同名，把加密和未加密的jar区别开，避免引起误会，同事之前踩过这个坑，多点了一次upload，上传了个反复加密的补丁）

**Comment by directionyu** [comment]
原来是这样, 一直debug还没意识到是重复加密的问题哈.. 直接屏蔽加密代码拿原始补丁测试了, 416837285 大佬加一下qq吧,有问题可以及时沟通.

**Comment by directionyu** [comment]
还有个问题 ,如果新增类 中有方法用到了回调, 比如kotlin 中 download(url, object : Callback<Any> {} , 回调的方法smail中会被编译在 download$1 引用,  但是补丁并没有生成回调方法的类

**Comment by feelschaotic** [comment]
因为Callback相当于是个类，所以需要在Callback上也加上@Add，你可以这么写 download(url, object : MyCallback {})  自定义一个MyCallback继承Callback，给MyCallback加上@Add

**Comment by directionyu** [comment]
典型场景使用Runnable
val runnable = Runnable {
xxxxx
}
instance!!.executorSupplier.forNetworkTasks().submit(runnable)

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xx/xx/xx/xx$Test$runnable$1;

补丁中只生成Test类,但是并没有生成runnable 的实现

**Comment by feelschaotic** [comment]
类是生成了，但是补丁没打包进来，所以可以尝试下我上面提到的方法，new子类 给子类加@Add

**Comment by directionyu** [comment]
还是不行,Robust 的issues https://github.com/Meituan-Dianping/Robust/issues/368 这个描述的跟我这个issurs差不多,  我反编译正常编译构建的Apk和补丁,发现很多东西都没有生成,比如权限请求的回调,动态广播回调,线程池的具体实现,, 难道补丁只能处理最简单的代码?
