### ISSUE TITLE
gradle3.2.0打包异常

### ISSUE THREAD

**Issue by TomFigter** [feelschaotic/SDKHotFix#8]
![image](https://user-images.githubusercontent.com/13266356/88246846-5800d400-ccce-11ea-8e37-64cf27ccd8fc.png)

![image](https://user-images.githubusercontent.com/13266356/88246820-3c95c900-ccce-11ea-810a-93cc462ba6e1.png)

**Comment by feelschaotic** [comment]
gradle版本不同  所以API有些变动  源码都有  你可以先看看Gradle文档修改下task  我抽空兼容下  不过最近非常忙  没有太多精力投入在开源项目上
